---
version: '3.7'
services:
  aws:
    image: localstack/localstack:0.9.0
    environment:
      # See: https://github.com/localstack/localstack#configurations
      - "SERVICES=dynamodb,kinesis,cloudwatch"
      - "DEFAULT_REGION=us-east-1"
      - "USE_SSL=true"
      - "START_WEB=0"
    ports:
      - "4568:4568"  # Kinesis
      - "4569:4569"  # DynamoDB
      - "4582:4582"  # Cloudwatch
      - "8080:8080"  # The control UI
